### ISSUE TITLE
SecurityGroup documentation error

### ISSUE THREAD

**Issue by zcq98** [kubeovn/docs#137]
按照[SecurityGroup配置文档](https://kubeovn.github.io/docs/v1.12.x/advance/security-group/)测试安全组发现和预期效果不一致

安全组配置如下：放行网关192.50.0.1以及禁止192.50.0.3

```yaml
apiVersion: kubeovn.io/v1
kind: SecurityGroup
metadata:
  name: sg-gw-both
spec:
  allowSameGroupTraffic: true
  egressRules:
  - ipVersion: ipv4
    policy: deny
    priority: 2
    protocol: all
    remoteAddress: 192.50.0.3/24
    remoteType: address
  - ipVersion: ipv4
    policy: allow
    priority: 1
    protocol: all
    remoteAddress: 192.50.0.1/24
    remoteType: address
  ingressRules:
  - ipVersion: ipv4
    policy: deny
    priority: 2
    protocol: icmp
    remoteAddress: 192.50.0.3/24
    remoteType: address
  - ipVersion: ipv4
    policy: allow
    priority: 1
    protocol: all
    remoteAddress: 192.50.0.1/24
    remoteType: address
```

实际情况发现192.50.0.3并未被禁止，查看 ACL 规则发现规则被正常下发：

```shell
$ kubectl ko nbctl acl-list ovn.sg.sg.gw.both
from-lport  2299 (inport == @ovn.sg.sg.gw.both && ip4 && ip4.dst == 192.50.0.1/24) allow-related
from-lport  2298 (inport == @ovn.sg.sg.gw.both && ip4 && ip4.dst == 192.50.0.3/24) drop
from-lport  2004 (inport == @ovn.sg.sg.gw.both && ip4 && ip4.dst == $ovn.sg.sg.gw.both.associated.v4) allow-related
from-lport  2004 (inport == @ovn.sg.sg.gw.both && ip6 && ip6.dst == $ovn.sg.sg.gw.both.associated.v6) allow-related
  to-lport  2299 (outport == @ovn.sg.sg.gw.both && ip4 && ip4.src == 192.50.0.1/24) allow-related
  to-lport  2298 (outport == @ovn.sg.sg.gw.both && ip4 && ip4.src == 192.50.0.3/24 && icmp4) drop
  to-lport  2005 (inport == @ovn.sg.sg.gw.both && arp) allow-related
  to-lport  2005 (inport == @ovn.sg.sg.gw.both && icmp6.type == {130, 133, 135, 136} && icmp6.code == 0 && ip.ttl == 255) allow-related
  to-lport  2005 (inport == @ovn.sg.sg.gw.both && ip.proto == 112) allow-related
  to-lport  2005 (inport == @ovn.sg.sg.gw.both && udp.src == 546 && udp.dst == 547 && ip6) allow-related
  to-lport  2005 (inport == @ovn.sg.sg.gw.both && udp.src == 68 && udp.dst == 67 && ip4) allow-related
  to-lport  2005 (outport == @ovn.sg.sg.gw.both && arp) allow-related
  to-lport  2005 (outport == @ovn.sg.sg.gw.both && icmp6.type == {130, 134, 135, 136} && icmp6.code == 0 && ip.ttl == 255) allow-related
  to-lport  2005 (outport == @ovn.sg.sg.gw.both && ip.proto == 112) allow-related
  to-lport  2005 (outport == @ovn.sg.sg.gw.both && udp.src == 547 && udp.dst == 546 && ip6) allow-related
  to-lport  2005 (outport == @ovn.sg.sg.gw.both && udp.src == 67 && udp.dst == 68 && ip4) allow-related
  to-lport  2004 (outport == @ovn.sg.sg.gw.both && ip4 && ip4.src == $ovn.sg.sg.gw.both.associated.v4) allow-related
  to-lport  2004 (outport == @ovn.sg.sg.gw.both && ip6 && ip6.src == $ovn.sg.sg.gw.both.associated.v6) allow-related
```

通过kubectl ko trace跟踪流表得到如下结果：

```shell
# busybox01 是启用安全组的 Pod，其 IP 为 192.50.0.2
kubectl ko trace vpc1/busybox01 192.50.0.3 icmp
+ kubectl exec ovn-central-674d5cb9d-t66rc -n kube-system -c ovn-central -- ovn-trace vpc1-subnet1 'inport == "busybox01.vpc1" && ip.ttl == 64 && icmp && eth.src == 00:00:00:CD:2F:58 && ip4.src == 192.50.0.2 && eth.dst == 00:00:00:AE:3E:16 && ip4.dst == 192.50.0.3 && ct.new'

ingress(dp="vpc1-subnet1", inport="busybox01.vpc1")
---------------------------------------------------
 0. ls_in_check_port_sec (northd.c:8603): 1, priority 50, uuid 6aea41c7
    reg0[15] = check_in_port_sec();
    next;
 4. ls_in_pre_acl (northd.c:5896): ip, priority 100, uuid 0194d5d4
    reg0[0] = 1;
    next;
 6. ls_in_pre_stateful (northd.c:6114): reg0[0] == 1, priority 100, uuid e2b2e041
    ct_next;

ct_next(ct_state=est|trk /* default (use --ct to customize) */)
---------------------------------------------------------------
 7. ls_in_acl_hint (northd.c:6202): !ct.new && ct.est && !ct.rpl && ct_mark.blocked == 0, priority 4, uuid c004fd96
    reg0[8] = 1;
    reg0[10] = 1;
    next;
 8. ls_in_acl (northd.c:6444): reg0[8] == 1 && (inport == @ovn.sg.sg.gw.both && ip4 && ip4.dst == 192.50.0.1/24), priority 3299, uuid f036168e
    next;

-----------------------------------------------------------------
```

部分逻辑流表如上所示，查看table 8 中的 ls_in_acl 发现：

```
 8. ls_in_acl (northd.c:6444): reg0[8] == 1 && (inport == @ovn.sg.sg.gw.both && ip4 && ip4.dst == 192.50.0.1/24), priority 3299, uuid f036168e
    next;
```

192.50.0.3 并未匹配 192.50.0.3/24，似乎在下发 ACL 时若携带掩码则被当作网段进行匹配，因此 192.50.0.3/24 的规则不会被匹配中

将安全组中的 remoteAddress 的 IP 掩码去除后，安全组达到预期的效果
